server:
  port: 8082
spring:
  datasource:
    password: admin
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: system
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp  jpa:    open-in-view: true
